package View;
import Config.ApplicationThemeUtility;
import java.awt.Color;
public class EmployeeUI extends javax.swing.JFrame {
     

    /**
     * Creates new form DashboardView
     */
    public EmployeeUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        dashboardPanel = new javax.swing.JPanel();
        dashboardLbl = new javax.swing.JLabel();
        dashboard_icon = new javax.swing.JLabel();
        employeeRecordsPanel = new javax.swing.JPanel();
        employeeRecordsLbl = new javax.swing.JLabel();
        employeeRecordsIcon = new javax.swing.JLabel();
        payrollPanel = new javax.swing.JPanel();
        payrollLbl = new javax.swing.JLabel();
        payrollIcon = new javax.swing.JLabel();
        leavePanel = new javax.swing.JPanel();
        leaveLbl = new javax.swing.JLabel();
        leaveIcon = new javax.swing.JLabel();
        attendancePanel = new javax.swing.JPanel();
        attendanceLbl = new javax.swing.JLabel();
        attendanceIcon = new javax.swing.JLabel();
        accountPanel = new javax.swing.JPanel();
        accountLbl = new javax.swing.JLabel();
        accountIcon = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        menuTabs = new javax.swing.JTabbedPane();
        dashboardTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        empRecordsTab = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        payslipTab = new javax.swing.JPanel();
        leaveTab = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        attendanceTab = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        accountTab = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MotorPH Payroll");
        setExtendedState(AdministratorUI.MAXIMIZED_BOTH);
        setMinimumSize(new java.awt.Dimension(1339, 832));
        setName("dashboardFrame"); // NOI18N
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        menuPanel.setBackground(new java.awt.Color(0, 0, 102));
        menuPanel.setName("menuPanel"); // NOI18N

        dashboardPanel.setBackground(new java.awt.Color(0, 0, 102));
        dashboardPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardPanel.setName("dashboardPanel"); // NOI18N
        dashboardPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardPanelMouseExited(evt);
            }
        });

        dashboardLbl.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        dashboardLbl.setForeground(new java.awt.Color(255, 255, 255));
        dashboardLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardLbl.setText("Dashboard");
        dashboardLbl.setToolTipText("");
        dashboardLbl.setName("dashboardLbl"); // NOI18N
        dashboardLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardLblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                goToDashboardTab(evt);
            }
        });

        dashboard_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboard_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_icons/dashboard_icon.png"))); // NOI18N
        dashboard_icon.setName("dashboard_icon"); // NOI18N
        dashboard_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboard_iconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboard_iconMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dashboard_iconMousePressed(evt);
            }
        });

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(dashboard_icon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(dashboard_icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashboardLbl)
                .addContainerGap())
        );

        employeeRecordsPanel.setBackground(new java.awt.Color(0, 0, 102));
        employeeRecordsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employeeRecordsPanel.setName("employeeRecordsPanel"); // NOI18N

        employeeRecordsLbl.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        employeeRecordsLbl.setForeground(new java.awt.Color(255, 255, 255));
        employeeRecordsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeRecordsLbl.setText("Employee");
        employeeRecordsLbl.setName("employeeRecordsLbl"); // NOI18N
        employeeRecordsLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employeeRecordsLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeeRecordsLblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                goToEmpRecordsTab(evt);
            }
        });

        employeeRecordsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_icons/employee_icon.png"))); // NOI18N
        employeeRecordsIcon.setName("employeeRecordsIcon"); // NOI18N
        employeeRecordsIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employeeRecordsIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeeRecordsIconMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                employeeRecordsIconMousePressed(evt);
            }
        });

        javax.swing.GroupLayout employeeRecordsPanelLayout = new javax.swing.GroupLayout(employeeRecordsPanel);
        employeeRecordsPanel.setLayout(employeeRecordsPanelLayout);
        employeeRecordsPanelLayout.setHorizontalGroup(
            employeeRecordsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeRecordsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeeRecordsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(employeeRecordsPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(employeeRecordsIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        employeeRecordsPanelLayout.setVerticalGroup(
            employeeRecordsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeRecordsPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(employeeRecordsIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeRecordsLbl)
                .addGap(12, 12, 12))
        );

        payrollPanel.setBackground(new java.awt.Color(0, 0, 102));
        payrollPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payrollPanel.setName("payrollPanel"); // NOI18N
        payrollPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                payrollPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                payrollPanelMouseExited(evt);
            }
        });

        payrollLbl.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        payrollLbl.setForeground(new java.awt.Color(255, 255, 255));
        payrollLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        payrollLbl.setText("Salary");
        payrollLbl.setName("payrollLbl"); // NOI18N
        payrollLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                payrollLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                payrollLblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                goToPayrollTab(evt);
            }
        });

        payrollIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        payrollIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_icons/salary_icon.png"))); // NOI18N
        payrollIcon.setName("payrollIcon"); // NOI18N
        payrollIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                payrollIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                payrollIconMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                payrollIconMousePressed(evt);
            }
        });

        javax.swing.GroupLayout payrollPanelLayout = new javax.swing.GroupLayout(payrollPanel);
        payrollPanel.setLayout(payrollPanelLayout);
        payrollPanelLayout.setHorizontalGroup(
            payrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payrollPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(payrollLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(payrollPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(payrollIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        payrollPanelLayout.setVerticalGroup(
            payrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, payrollPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(payrollIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payrollLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        leavePanel.setBackground(new java.awt.Color(0, 0, 102));
        leavePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leavePanel.setName("leavePanel"); // NOI18N
        leavePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leavePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leavePanelMouseExited(evt);
            }
        });

        leaveLbl.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        leaveLbl.setForeground(new java.awt.Color(255, 255, 255));
        leaveLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leaveLbl.setText("Leave ");
        leaveLbl.setName("leaveLbl"); // NOI18N
        leaveLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leaveLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leaveLblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                goToLeaveTab(evt);
            }
        });

        leaveIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leaveIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_icons/leave_manager_icon.png"))); // NOI18N
        leaveIcon.setName("leaveIcon"); // NOI18N
        leaveIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leaveIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leaveIconMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                leaveIconMousePressed(evt);
            }
        });

        javax.swing.GroupLayout leavePanelLayout = new javax.swing.GroupLayout(leavePanel);
        leavePanel.setLayout(leavePanelLayout);
        leavePanelLayout.setHorizontalGroup(
            leavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leavePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leaveLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(leavePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(leaveIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leavePanelLayout.setVerticalGroup(
            leavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leavePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leaveIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leaveLbl)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        attendancePanel.setBackground(new java.awt.Color(0, 0, 102));
        attendancePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attendancePanel.setName("attendancePanel"); // NOI18N
        attendancePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                attendancePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                attendancePanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                attendancePanelMousePressed(evt);
            }
        });

        attendanceLbl.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        attendanceLbl.setForeground(new java.awt.Color(255, 255, 255));
        attendanceLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attendanceLbl.setText("Attendance");
        attendanceLbl.setName("attendanceLbl"); // NOI18N
        attendanceLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                attendanceLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                attendanceLblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                attendanceLblMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                goToAttendanceTab(evt);
            }
        });

        attendanceIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attendanceIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_icons/attendance_icon.png"))); // NOI18N
        attendanceIcon.setName("attendanceIcon"); // NOI18N
        attendanceIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                attendanceIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                attendanceIconMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                attendanceIconMousePressed(evt);
            }
        });

        javax.swing.GroupLayout attendancePanelLayout = new javax.swing.GroupLayout(attendancePanel);
        attendancePanel.setLayout(attendancePanelLayout);
        attendancePanelLayout.setHorizontalGroup(
            attendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attendancePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(attendanceLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(attendancePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(attendanceIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        attendancePanelLayout.setVerticalGroup(
            attendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendancePanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(attendanceIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attendanceLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        accountPanel.setBackground(new java.awt.Color(0, 0, 102));
        accountPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accountPanel.setName("accountPanel"); // NOI18N
        accountPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accountPanelMousePressed(evt);
            }
        });

        accountLbl.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        accountLbl.setForeground(new java.awt.Color(255, 255, 255));
        accountLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountLbl.setText("Account");
        accountLbl.setName("accountLbl"); // NOI18N
        accountLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountLblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                goToAccountTab(evt);
            }
        });

        accountIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_icons/profile_icon.png"))); // NOI18N
        accountIcon.setName("accountIcon"); // NOI18N
        accountIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountIconMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accountIconMousePressed(evt);
            }
        });

        javax.swing.GroupLayout accountPanelLayout = new javax.swing.GroupLayout(accountPanel);
        accountPanel.setLayout(accountPanelLayout);
        accountPanelLayout.setHorizontalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountPanelLayout.createSequentialGroup()
                        .addComponent(accountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountPanelLayout.createSequentialGroup()
                        .addComponent(accountIcon)
                        .addGap(22, 22, 22)))
                .addContainerGap(6, Short.MAX_VALUE))
        );
        accountPanelLayout.setVerticalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(accountIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(0, 0, 102));
        jPanel11.setName("jPanel11"); // NOI18N

        jLabel36.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("LOGOUT");
        jLabel36.setName("jLabel36"); // NOI18N

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_icons/logout_icon.png"))); // NOI18N
        jLabel37.setName("jLabel37"); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel37)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(leavePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payrollPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(employeeRecordsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashboardPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attendancePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(dashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(employeeRecordsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(payrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(leavePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(attendancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(accountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        getContentPane().add(menuPanel);
        menuPanel.setBounds(0, 0, 100, 1160);

        headerPanel.setBackground(new java.awt.Color(0, 0, 153));
        headerPanel.setName("headerPanel"); // NOI18N

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1830, Short.MAX_VALUE)
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(headerPanel);
        headerPanel.setBounds(100, -20, 1830, 40);

        menuTabs.setBackground(new java.awt.Color(255, 255, 255));
        menuTabs.setName("menuTabs"); // NOI18N

        dashboardTab.setBackground(new java.awt.Color(255, 255, 255));
        dashboardTab.setName("dashboardTab"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setText("Dashboard");
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout dashboardTabLayout = new javax.swing.GroupLayout(dashboardTab);
        dashboardTab.setLayout(dashboardTabLayout);
        dashboardTabLayout.setHorizontalGroup(
            dashboardTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardTabLayout.createSequentialGroup()
                .addGap(584, 584, 584)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1095, Short.MAX_VALUE))
        );
        dashboardTabLayout.setVerticalGroup(
            dashboardTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardTabLayout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(713, Short.MAX_VALUE))
        );

        menuTabs.addTab("Dashboard", dashboardTab);

        empRecordsTab.setBackground(new java.awt.Color(255, 255, 255));
        empRecordsTab.setName("empRecordsTab"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel2.setText("Employee Records");
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout empRecordsTabLayout = new javax.swing.GroupLayout(empRecordsTab);
        empRecordsTab.setLayout(empRecordsTabLayout);
        empRecordsTabLayout.setHorizontalGroup(
            empRecordsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empRecordsTabLayout.createSequentialGroup()
                .addGap(514, 514, 514)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1023, Short.MAX_VALUE))
        );
        empRecordsTabLayout.setVerticalGroup(
            empRecordsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empRecordsTabLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(727, Short.MAX_VALUE))
        );

        menuTabs.addTab("EmployeeRecords", empRecordsTab);

        payslipTab.setBackground(new java.awt.Color(255, 255, 255));
        payslipTab.setName("payslipTab"); // NOI18N

        javax.swing.GroupLayout payslipTabLayout = new javax.swing.GroupLayout(payslipTab);
        payslipTab.setLayout(payslipTabLayout);
        payslipTabLayout.setHorizontalGroup(
            payslipTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1870, Short.MAX_VALUE)
        );
        payslipTabLayout.setVerticalGroup(
            payslipTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );

        menuTabs.addTab("Payroll", payslipTab);

        leaveTab.setBackground(new java.awt.Color(255, 255, 255));
        leaveTab.setName("leaveTab"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel4.setText("Leave Manager");
        jLabel4.setName("jLabel4"); // NOI18N

        javax.swing.GroupLayout leaveTabLayout = new javax.swing.GroupLayout(leaveTab);
        leaveTab.setLayout(leaveTabLayout);
        leaveTabLayout.setHorizontalGroup(
            leaveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leaveTabLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1519, Short.MAX_VALUE))
        );
        leaveTabLayout.setVerticalGroup(
            leaveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leaveTabLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1017, Short.MAX_VALUE))
        );

        menuTabs.addTab("Leave", leaveTab);

        attendanceTab.setBackground(new java.awt.Color(255, 255, 255));
        attendanceTab.setName("attendanceTab"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel5.setText("Attendance");
        jLabel5.setName("jLabel5"); // NOI18N

        javax.swing.GroupLayout attendanceTabLayout = new javax.swing.GroupLayout(attendanceTab);
        attendanceTab.setLayout(attendanceTabLayout);
        attendanceTabLayout.setHorizontalGroup(
            attendanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendanceTabLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1519, Short.MAX_VALUE))
        );
        attendanceTabLayout.setVerticalGroup(
            attendanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendanceTabLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1017, Short.MAX_VALUE))
        );

        menuTabs.addTab("Attendance", attendanceTab);

        accountTab.setBackground(new java.awt.Color(255, 255, 255));
        accountTab.setName("accountTab"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel6.setText("User Account");
        jLabel6.setName("jLabel6"); // NOI18N

        javax.swing.GroupLayout accountTabLayout = new javax.swing.GroupLayout(accountTab);
        accountTab.setLayout(accountTabLayout);
        accountTabLayout.setHorizontalGroup(
            accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountTabLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1519, Short.MAX_VALUE))
        );
        accountTabLayout.setVerticalGroup(
            accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountTabLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1017, Short.MAX_VALUE))
        );

        menuTabs.addTab("Account", accountTab);

        getContentPane().add(menuTabs);
        menuTabs.setBounds(100, 10, 1870, 1150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goToDashboardTab(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToDashboardTab
        // TODO add your handling code here:
        menuTabs.setSelectedIndex(0);
    }//GEN-LAST:event_goToDashboardTab

    private void goToEmpRecordsTab(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToEmpRecordsTab
        // TODO add your handling code here:
        menuTabs.setSelectedIndex(1);
    }//GEN-LAST:event_goToEmpRecordsTab

    private void goToPayrollTab(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToPayrollTab
        // TODO add your handling code here:
        menuTabs.setSelectedIndex(2);
    }//GEN-LAST:event_goToPayrollTab

    private void goToLeaveTab(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToLeaveTab
        // TODO add your handling code here:
        menuTabs.setSelectedIndex(3);
    }//GEN-LAST:event_goToLeaveTab

    private void goToAttendanceTab(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToAttendanceTab
        // TODO add your handling code here:
        menuTabs.setSelectedIndex(4);
    }//GEN-LAST:event_goToAttendanceTab

    private void goToAccountTab(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToAccountTab
        // TODO add your handling code here:
        menuTabs.setSelectedIndex(5);
    }//GEN-LAST:event_goToAccountTab

    private void dashboard_iconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_iconMousePressed
        //Navigates to Dashboard Tab
        menuTabs.setSelectedIndex(0);
    }//GEN-LAST:event_dashboard_iconMousePressed

    private void employeeRecordsIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeRecordsIconMousePressed
        //Navigates to Employee Records Tab
        menuTabs.setSelectedIndex(1);
    }//GEN-LAST:event_employeeRecordsIconMousePressed

    private void payrollIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payrollIconMousePressed
        //Navigates to Payroll Tab
        menuTabs.setSelectedIndex(2);
    }//GEN-LAST:event_payrollIconMousePressed

    private void leaveIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leaveIconMousePressed
        //Navigates to Leave Tab
        menuTabs.setSelectedIndex(3);
    }//GEN-LAST:event_leaveIconMousePressed

    private void attendanceIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceIconMousePressed
        //Navigates to Attendance Tab
        menuTabs.setSelectedIndex(4);
    }//GEN-LAST:event_attendanceIconMousePressed

    private void accountIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountIconMousePressed
        //Navigates to Account Tab
        menuTabs.setSelectedIndex(5);
    }//GEN-LAST:event_accountIconMousePressed

    private void dashboardPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMouseEntered
        // TODO add your handling code here:
        dashboardPanel.setBackground(new Color(0,0,140));
    }//GEN-LAST:event_dashboardPanelMouseEntered

    private void dashboardPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMouseExited
        // TODO add your handling code here:
        dashboardPanel.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_dashboardPanelMouseExited

    private void dashboard_iconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_iconMouseEntered
        // TODO add your handling code here:
        dashboardPanel.setBackground(new Color(0,0,140));
    }//GEN-LAST:event_dashboard_iconMouseEntered

    private void dashboard_iconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_iconMouseExited
        // TODO add your handling code here:
        dashboardPanel.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_dashboard_iconMouseExited

    private void employeeRecordsIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeRecordsIconMouseEntered
        // TODO add your handling code here:
        employeeRecordsPanel.setBackground(new Color(0,0,140));
    }//GEN-LAST:event_employeeRecordsIconMouseEntered

    private void employeeRecordsIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeRecordsIconMouseExited
        // TODO add your handling code here:
        employeeRecordsPanel.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_employeeRecordsIconMouseExited

    private void payrollPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payrollPanelMouseEntered
        // TODO add your handling code here:
        payrollPanel.setBackground(new Color(0,0,140));
    }//GEN-LAST:event_payrollPanelMouseEntered

    private void payrollPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payrollPanelMouseExited
        // TODO add your handling code here:
        payrollPanel.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_payrollPanelMouseExited

    private void payrollIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payrollIconMouseEntered
        // TODO add your handling code here:
        payrollPanel.setBackground(new Color(0,0,140));
    }//GEN-LAST:event_payrollIconMouseEntered

    private void payrollIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payrollIconMouseExited
        // TODO add your handling code here:
        payrollPanel.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_payrollIconMouseExited

    private void leaveIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leaveIconMouseEntered
        // TODO add your handling code here:
        leavePanel.setBackground(new Color(0,0,140));
    }//GEN-LAST:event_leaveIconMouseEntered

    private void leaveIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leaveIconMouseExited
        // TODO add your handling code here:
        leavePanel.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_leaveIconMouseExited

    private void attendanceIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceIconMouseEntered
        // TODO add your handling code here:
        attendancePanel.setBackground(new Color(0,0,140));
    }//GEN-LAST:event_attendanceIconMouseEntered

    private void attendanceIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceIconMouseExited
        // TODO add your handling code here:
        attendancePanel.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_attendanceIconMouseExited

    private void accountIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountIconMouseEntered
        // TODO add your handling code here:
        accountPanel.setBackground(new Color(0,0,140));
    }//GEN-LAST:event_accountIconMouseEntered

    private void accountIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountIconMouseExited
        // TODO add your handling code here:
        accountPanel.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_accountIconMouseExited

    private void dashboardLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardLblMouseEntered
        // TODO add your handling code here:
        dashboardPanel.setBackground(new Color(0,0,140));
    }//GEN-LAST:event_dashboardLblMouseEntered

    private void dashboardLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardLblMouseExited
        // TODO add your handling code here:
        dashboardPanel.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_dashboardLblMouseExited

    private void employeeRecordsLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeRecordsLblMouseEntered
        // TODO add your handling code here:
        employeeRecordsPanel.setBackground(new Color(0,0,140));
    }//GEN-LAST:event_employeeRecordsLblMouseEntered

    private void employeeRecordsLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeRecordsLblMouseExited
        // TODO add your handling code here:
        employeeRecordsPanel.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_employeeRecordsLblMouseExited

    private void leavePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavePanelMouseEntered
        // TODO add your handling code here:
        leavePanel.setBackground(new Color(0,0,140));
    }//GEN-LAST:event_leavePanelMouseEntered

    private void leavePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavePanelMouseExited
        // TODO add your handling code here:
        leavePanel.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_leavePanelMouseExited

    private void payrollLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payrollLblMouseEntered
        // TODO add your handling code here:
        payrollPanel.setBackground(new Color(0,0,140));
    }//GEN-LAST:event_payrollLblMouseEntered

    private void payrollLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payrollLblMouseExited
        // TODO add your handling code here:
        payrollPanel.setBackground(new Color(0,0,102));      
    }//GEN-LAST:event_payrollLblMouseExited

    private void leaveLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leaveLblMouseEntered
        // TODO add your handling code here:
        leavePanel.setBackground(new Color(0,0,140));
    }//GEN-LAST:event_leaveLblMouseEntered

    private void leaveLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leaveLblMouseExited
        // TODO add your handling code here:
        leavePanel.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_leaveLblMouseExited

    private void attendanceLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceLblMouseEntered
        // TODO add your handling code here:
        attendancePanel.setBackground(new Color(0,0,140));
    }//GEN-LAST:event_attendanceLblMouseEntered

    private void attendanceLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceLblMouseExited
        // TODO add your handling code here:
        attendancePanel.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_attendanceLblMouseExited

    private void accountLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountLblMouseEntered
        // TODO add your handling code here:
        accountPanel.setBackground(new Color(0,0,140));
    }//GEN-LAST:event_accountLblMouseEntered

    private void accountLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountLblMouseExited
        // TODO add your handling code here:
        accountPanel.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_accountLblMouseExited

    private void attendanceLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceLblMousePressed
        // TODO add your handling code here:
        menuTabs.setSelectedIndex(4);
    }//GEN-LAST:event_attendanceLblMousePressed

    private void attendancePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancePanelMouseEntered
        // TODO add your handling code here:
        attendancePanel.setBackground(new Color(0,0,140));
    }//GEN-LAST:event_attendancePanelMouseEntered

    private void attendancePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancePanelMouseExited
        // TODO add your handling code here:
        attendancePanel.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_attendancePanelMouseExited

    private void attendancePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancePanelMousePressed
        // TODO add your handling code here:
        menuTabs.setSelectedIndex(4);
    }//GEN-LAST:event_attendancePanelMousePressed

    private void accountPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountPanelMouseEntered
        // TODO add your handling code here:
        accountPanel.setBackground(new Color(0,0,140));
    }//GEN-LAST:event_accountPanelMouseEntered

    private void accountPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountPanelMouseExited
        // TODO add your handling code here:
        accountPanel.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_accountPanelMouseExited

    private void accountPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountPanelMousePressed
        // TODO add your handling code here:
        menuTabs.setSelectedIndex(5);
    }//GEN-LAST:event_accountPanelMousePressed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        ApplicationThemeUtility.setIntelliJ();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new EmployeeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountIcon;
    private javax.swing.JLabel accountLbl;
    private javax.swing.JPanel accountPanel;
    private javax.swing.JPanel accountTab;
    private javax.swing.JLabel attendanceIcon;
    private javax.swing.JLabel attendanceLbl;
    private javax.swing.JPanel attendancePanel;
    private javax.swing.JPanel attendanceTab;
    private javax.swing.JLabel dashboardLbl;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JPanel dashboardTab;
    private javax.swing.JLabel dashboard_icon;
    private javax.swing.JPanel empRecordsTab;
    private javax.swing.JLabel employeeRecordsIcon;
    private javax.swing.JLabel employeeRecordsLbl;
    private javax.swing.JPanel employeeRecordsPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JLabel leaveIcon;
    private javax.swing.JLabel leaveLbl;
    private javax.swing.JPanel leavePanel;
    private javax.swing.JPanel leaveTab;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTabbedPane menuTabs;
    private javax.swing.JLabel payrollIcon;
    private javax.swing.JLabel payrollLbl;
    private javax.swing.JPanel payrollPanel;
    private javax.swing.JPanel payslipTab;
    // End of variables declaration//GEN-END:variables
}
